name: Generate Snake

on:
  # हर 24 घंटे में अपने आप चलेगा
  schedule:
    - cron: "0 */24 * * *"
  
  # जब भी तुम चाहो मैन्युअली भी रन कर सकती हो
  workflow_dispatch:
  
  # जब भी मुख्य ब्रांच पर पुश होगा
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generates a game with a snake eating your contributions graph
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Push the content to a special output branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
